version: "2.4"
services:
  mongodb:
    image: mongo:latest
    container_name: my-mongodb-container
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  backend:
    build: .
    container_name: my-nodejs-app
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    env_file: .env

volumes:
  mongodb-data:
